# yamllint disable rule:line-length
name: codecov
'on':
  workflow_dispatch:
jobs:
  codecov:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          arch: arm64
          runner: macos-latest
          expander_leg: macos-latest--arm64
    timeout-minutes: 15
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v6
      with:
        distribution: ${{ (runner.os == 'Windows' && matrix.arch == 'arm64') && 
          'microsoft' || 'temurin' }}
        java-version: ${{ (runner.os == 'Windows' && matrix.arch == 'arm64') && 
          '25' || '25.0.4+101.0.LTS' }}
        architecture: ${{ matrix.arch == 'arm64' && 'aarch64' || 'x64' }}
    - uses: actions/cache@v6
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-
    - uses: docker/setup-qemu-action@v3
      if: runner.os == 'Linux' && matrix.arch == 'arm64'
      with:
        platforms: amd64
    - run: mvn install -Pjacoco
    - uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    name: codecov [${{ matrix.expander_leg }}]
